export const episodes = [
  { title: "Episódio 1", link: "https://www.instagram.com/reel/DGX4wLTu_eP/?igsh=MnJhNW1vY2txMGdj" },
  { title: "Episódio 2", link: "https://www.instagram.com/reel/DGp6CaqO--v/?igsh=MTNkMjg2YmUxZmUwcw==" },
  { title: "Episódio 3", link: "https://www.instagram.com/reel/DG74vsnuc_p/?igsh=MTY4M3NmM3VucjhmOA==" },
  { title: "Episódio 4", link: "https://www.instagram.com/reel/DHOzFh-pOUz/?igsh=MW5wdXVvZTNpdnZmdw==" },
  { title: "Episódio 5", link: "https://www.instagram.com/reel/DHg_3A4hVsj/?igsh=MTkyc2pkZWM2ZXFsdA==" },
  { title: "Episódio 6", link: "https://www.instagram.com/reel/DHy8ov0pm5f/?igsh=MW9zOXIwNGxlMTN5Nw==" },
  { title: "Episódio 7", link: "https://www.instagram.com/reel/DIEO4U9O-Uw/?igsh=c3B4dXAxYjhmYWpx" },
  { title: "Episódio 8", link: "https://www.instagram.com/reel/DIXIH9cB7wo/?igsh=MXgyaWh1YWtmc2Z0ZQ==" },
  { title: "Episódio 9", link: "https://www.instagram.com/reel/DKCgc7BtnhW/?igsh=dGdwbG0xejA1ODBk" },
  { title: "Episódio 10", link: "https://www.instagram.com/reel/DKVFpTKJeNh/?igsh=MXBmZWQ1OW5pazJmag==" },
  { title: "Episódio 11", link: "https://www.instagram.com/reel/DLLe4VFJIR-/?igsh=MWN3a3plNm55eHduZA==" },
  { title: "Episódio 12", link: "https://www.instagram.com/reel/DLcSXx-u2tX/?igsh=MTdmdnM2cXFsbjhkcw==" },
  { title: "Episódio 13", link: "https://www.instagram.com/reel/DLx3CnmpM2Y/?igsh=MWxqMHo4eTY2aHhnaQ==" },
  { title: "Episódio 14", link: "https://www.instagram.com/reel/DMToWciJzno/?igsh=YWltaWZuZmRrNHg=" },
  { title: "Episódio 15", link: "https://www.instagram.com/reel/DMBoPyuJPmL/?igsh=ajQxNmNsNnU1b2dh" },
  { title: "Episódio 16", link: "https://www.instagram.com/reel/DM2feZ_Ow3n/?igsh=MW43MWEzYnhhaXVzeA==" },
  { title: "Episódio 17", link: "https://www.instagram.com/reel/DNdA4B2NMau/?igsh=emZxa3FwMWZuOWFm" },
  { title: "Episódio 18", link: "https://www.instagram.com/reel/DORha0JASYy/?igsh=OWt3dmp1bWJ5cm1h" },
  { title: "Episódio 19", link: "https://www.instagram.com/reel/DORha0JASYy/?igsh=OWt3dmp1bWJ5cm1h" },
  { title: "Episódio 20", link: "https://www.instagram.com/reel/DRFNsFxjZpB/?igsh=c2JtNXcwczA5OHQz" },
  { title: "Episódio 21", link: "https://www.instagram.com/reel/DSx1iIWjReT/?igsh=bTVmOXh0a2Q2bm5z" },
];